### ISSUE TITLE
can't scroll with keyboard in firefox

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-www#139]
original ticket: https://github.com/helm/helm/issues/4607

On docs.helm.sh using firefox, I can only scroll using my mouse's scroll wheel. Arrow keys, page up/down are both broken.

**Comment by sciurus** [comment]
I've reproduced this problem on Firefox Nightly and Firefox Beta.

It also affect scrolling via pressing the spacebar.

Scrolling via the keyboard works on Chrome and Safari.

**Comment by tjimsk** [comment]
Reporting scrolling problem with Safari 12.0.2 on laptop trackpad.  

The scroll event is sent to another element (likely the parent) first.  So in order to scroll up in the content view, its parent view must first be scrolled to its top, likewise in order to scroll down.

**Comment by bacongobbler** [comment]
It looks like this has been resolved. Closing!

**Comment by sciurus** [comment]
bacongobbler what makes you say this is resolved? I'm still experiencing the problem on both Firefox Beta and Nightly. For example, if I load https://helm.sh/docs/using_helm/#quickstart and press spacebar or the down arrow nothing happens.

**Comment by bacongobbler** [comment]
Okay, so you can't scroll the main body when you click links from the sidebar, but when you click links in the main body, scrolling works fine. For example, scrolling works when you click on the "quickstart guide" link from https://helm.sh/docs/. @tjimsk's assumption about the scroll event being sent to another element seems accurate.

FYI I clicked that link @sciurus and scrolling worked for me without an issue.

I'll re-open this since it still appears to occur in certain scenarios when interacting with the sidebar navigation menu.

**Comment by felixhummel** [comment]
This is a general problem.

Steps to reproduce:

- go to https://helm.sh/docs/using_helm/#role-based-access-control
- press Arrow keys or PageUp/PageDown

Expected: scrolls

Actual: nothing happens

**Comment by seandilda** [comment]
I have been struggling with this as well.  I've found that if you click the header bar (just to the left of the 'Get Helm' link, firefox will then let you use your keyboard to scroll through the outer frame.  However, if you click the inner frame, scrolling is locked and you can't use the keyboard to scroll.

It looks like using the keyboard causes firefox to scroll the outer frame.  Chrome appears to use the outer frame scrolling if you use the mouse or keyboard.

**Comment by flynnduism** [comment]
This issue is a weird one. I've investigated the strange behaviour in Firefox... when you change focus (i.e. clicking anything after the initial pageload) the scrolling with keys no longer works as expected.

I've experimented with different CSS edits to change how the main content column is positioned and nested to try and resolve this, but with no success. I'll continue investigating but unsure I'll find a way to resolve this.

I did find a setting ([http://kb.mozillazine.org/Accessibility.browsewithcaret](http://kb.mozillazine.org/Accessibility.browsewithcaret)) in Firefox that lets you enhance keyboard browsing controls to overcome the issue you're experiencing. 
![Screen Shot 2019-07-17 at 4 17 41 PM](https://user-images.githubusercontent.com/686194/61418194-97703580-a8ae-11e9-9db1-ee8ae98be954.png)

_(See the third checkbox under 'Browsing')_

Ideally we will change whatever aspect of the website is causing this issue, but until then this might help you.

**Comment by wisniewskit** [comment]
This turns out to be an interop issue with `overflow:scroll`. On my Linux box I see a second, disabled scrollbar on the content area which "breaks" the scrolling when focused. Sure enough, if I disable this CSS then that scrollbar goes away and I can scroll again:

```
.container-full {
  overflow-y: scroll;
}
```

Chrome is also showing the same "extra" scrollbar because of this CSS, but it does not seem to ignore the attempt to scroll, while Firefox does. I've reduced a test-case and filed [Firefox bug 1567237](https://bugzilla.mozilla.org/show_bug.cgi?id=1567237) to investigate further.

In the meantime, maybe `overflow-y: auto` is more appropriate here?

**Comment by flynnduism** [comment]
@wisniewskit you are my hero. Thanks so much for finding this! You are 100% correct.

I always assumed that `scroll` was a safe default as opposed to other values (`hidden`), but I am wrong. Using `auto` solves this strange behavior. Opened #242 to implement your fix.

**Comment by wisniewskit** [comment]
@flynnduism, no problem, I've been there before. I remember how strange it was the first time I realized that `scroll` basically means "always show scrollbars", while `auto` means "show scrollbars when necessary". It can even seem pointless, but that's what happens sometimes when there are two values to pick from :)

Feel free to check with us on the #webcompat Mozilla IRC (or ping on GitHub) if you ever run into other weirdness, especially when it seems like there is a an interop/webcompat issue. We're a small team, but we're happy to help as we can!

**Comment by emilio** [comment]
Should be fixed in the latest Firefox Nightly, though I need to say that the reasoning for the previous Firefox behavior made some sense to me. Obviously in this case it sucks though (thus the fix).
