### ISSUE TITLE
Why 2.14.0 docs

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#497]
In the UI we list links to docs for 3.1.0, 2.16, and 2.14. You can see this in the `config.toml` configuration:

https://github.com/helm/helm-www/blob/cacaa13201f35a73e591c51896c65f150be091a0/config.toml#L42-L44

Is there a reason we have 2.14 docs, a point frozen in time, for people to get to?

**Comment by flynnduism** [comment]
We can remove this if it doesn't seem useful... 

IMO if a major release still has people using it, we could preserve archival docs. It's pretty easy to generate these and doesn't cost anything. Though as per [this thread](https://github.com/helm/helm-www/pull/493#issuecomment-585871736) I'm not sure which releases are best archived in this way.

I will happily follow the wishes of you and the other maintainers on this.

**Comment by bridgetkromhout** [comment]
> IMO if a major release still has people using it, we could preserve archival docs.

For comparison, https://kubernetes.io/docs/home/ currently has docs for 5 minor releases. 

![image](https://user-images.githubusercontent.com/2104453/74958862-3625bd00-53cf-11ea-83ea-769a79bb17fa.png)

**Comment by mattfarina** [comment]
@bridgetkromhout The difference there is that each Kubernetes minor release is breaking in some way. Kubernetes does not follow semver when it comes to some things. Though, it is nice to have that.

@flynnduism On the helm dev call today we talked about this. It would be nice to have but we aren't consistently doing it right now. We have v2.14 and v2.16. But not v2.15. And docs for v2 and v3 are handled differently. How would we snapshot for v3.1, v3.2, etc? I don't think this is worked out.

If someone has time to make all of this work it would be great. If not, can we just keep the latest v2 and v3 until we have time to do it in full?

**Comment by bridgetkromhout** [comment]
@mattfarina I've thought about this on and off, and I think if we don't tag docs for every release. then it will be very confusing to people that we have docs for 2.14 and 2.16 (but not 2.15). And we have no way to indicate nuance around changes in docs from 3.0.x to 3.1.x to 3.2.x, etc.

So I think the most sustainable path forward (in terms of what we can realistically accomplish right now) is "most current v2 docs" and "most current v3 docs". @flynnduism, I've put in a PR to change this.

**Comment by bridgetkromhout** [comment]
Discussed this with @flynnduism and he's clarified that we _can_ support a range of release versions for the docs, but we'd need to figure out how to update the docs in sync with this. (I know there is a lot of work in the k8s project to update docs when features change.)

**Comment by flynnduism** [comment]
Thanks for the update in #603! 👏 

As you both note here, we haven't had any consistent process around mapping docs to releases. It's certainly doable (more on that below) but ultimately it depends on **whether or not we want to do so**. 

Would it be useful for Helm users? 
Do people seek out specific versions of Docs beyond v2 and v3?

I can't definitively answer the _why_ - but below have detailed the _how_. 

If we want to do detailed versioning, I can make the changes to (1) create archival subdomains and (2) update docs, readmes, create milestones etc to create this process.

---


## Simple Version 

If we want to continue with this simpler path and just work with 2 versions of the site (as per your edits in #603 @bridgetkromhout), I'd suggest we reflect this in the docs version names, presenting the docs as the latest state of the `master` and `dev-v2` branches rather than trying to reflect major or minor releases.

_Current labels:_

![Screen Shot 2020-04-29 at 10 24 23 AM](https://user-images.githubusercontent.com/686194/80626858-e59c9280-8a03-11ea-9d4d-aefb07eb611a.png)

_Simpler:_

![Screen Shot 2020-04-29 at 10 25 09 AM](https://user-images.githubusercontent.com/686194/80626872-ed5c3700-8a03-11ea-8c46-2bdf48c163e9.png)

---

## Detailed Versioning

As noted above, the process to create versions of the site is unclear and hasn't been applied to recent releases.

If we want to have more detailed versioning, there are clarifications and  process changes needed:

1. **Document the website versioning steps** - this has been missing so I've written up the steps to add a versioned subdomain for Helm.sh here: [https://hackmd.io/ZwZezCoiR2uVN4xbjhOC5A](https://hackmd.io/ZwZezCoiR2uVN4xbjhOC5A). 

    This process takes an estimated 5 to 10 minutes; basically you create an archival branch and deploy it to the Helm Netlify account. If we want to go this route I would update the release docs with this content. 

2. **Helm release process should ensure that helm-www is updated.** Currently, the processes around creating milestones and defining releases on helm/helm haven't been applied here. Updating the website is item #9 in the [Release Checklist](https://helm.sh/docs/community/release_checklist/#9-update-docs-site), but I haven't seen PRs to do so when a release is cut. 

    Typically I hear about a release from slack/twitter and then edit the site version info, but it's **reactive** and often well after the fact.
    
3. **Use the Helm milestones to apply the release timeline to docs**

    Currently, docs are often updated with fixes and corrections _after_ a release is cut, as issues are raised and addressed - so snapshotting docs at the same time as a 3.1.0 or 3.2.0 release could create confusion.

    I think the latest master of 'helm-www' should reflect the last release until the next one occurs. E.g. on the day of a 3.3 release:

    * site version is bumped from 3.2 to 3.3
    * site master is deployed as an archival 3-2-0.helm.sh


    Thus helm.sh shows the latest edits regarding the recent version (3.3), and 3-2-0.helm.sh is a snapshot of docs that include any edits for the period between 3.2 and 3.3.

    If a new feature or change is documented prior to the release (_yay!_), the change should not be merged and deployed until the release is officially cut and the archival process outlined above for docs is carried out - i.e. we freeze new content (not bug fixes) until release day. 

    That way `helm-www` can follow release milestones for issues and PRs like the main project and keep edits out of versions that they do not apply to.
    
I'd be happy to do the work to (1) update the docs, checklists etc to ensure it's clearly documented and part of the process and (2) go back and spin up archival urls for versions like https://v3-1-0.helm.sh/ - **if we deem it valuable to do so** and want to go that route!
