### ISSUE TITLE
Translate /i18n/zh.toml in Chinese

### ISSUE THREAD

**Issue by lou-lan** [helm/helm-www#618]
Translate /i18n/zh.toml in Chinese

**Comment by zhangqx2010** [comment]
@lucperkins nice to see you here! 👋 Several fellows here want to translate the doc into Chinese. Do you know is there any Chinese groups are doing this work?

**Comment by zhangqx2010** [comment]
Add @zgfh @bei612 here since I may slow response during working hours.

**Comment by bacongobbler** [comment]
> Do you know is there any Chinese groups are doing this work?

Not that we are aware of at this time!

**Comment by lucperkins** [comment]
@zhangqx2010 Oh hi! So good to hear from you 😄 I think that @bacongobbler, @flynnduism, @bridgetkromhout, and others will have a better sense of which efforts are currently underway. But from @bacongobbler it sounds like the path is clear. So glad that you all want to contribute!

**Comment by flynnduism** [comment]
+1 @zhangqx2010 any translations would be very welcome. ❤️ 

I can help if you have any questions or issues with working on the site! There's a guide here regarding [Contributing Translated Content](https://helm.sh/docs/community/localization/#translating-content) which is a good start.

**Comment by zhangqx2010** [comment]
Thanks @flynnduism. We will submit one proposal(mostly process) for Chinese translation in issue so that we can cut down overlap between two individual's work as much as possible.
I used to contribute to k8s docs. But these days I am really busy with company stuff so most of the translation work will probably be done with the fellows. @bei612 @zgfh will be the main contacts here. While I'd love to do reviewing work :smile:

**Comment by bridgetkromhout** [comment]
Thanks for getting this started!
